import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/Sidebar'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-full fixed w-screen overflow-x-none bg-gray-50">
          <div className="h-full md:flex w-56 md:flex-col inset-y-0 z-[80] bg-gray-900">
              <Sidebar/>
          </div>
      </div>
        {children}</body>
    </html>
); 
}
